backend:
  name: github
  repo: heidecjj/joshmakes
  branch: master
  # name: git-gateway
  # branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # - {label: "", name: "", widget: "", default: ""}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Featured Image", name: "featured-img", widget: "image"}
      - {label: "Mathjax", name: "mathjax", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
